#This parameter indicates that data augmentation will be applied during training
AUGMENTATION: True
# VGG16, for example, requires images of size 224x224 pixels, and the 3 represents the number of color channels (RGB).
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
 #A batch size of 16 means that 16 images will be processed together before the model updates its weights
BATCH_SIZE: 16
#only the convolutional layers of the model are loaded
INCLUDE_TOP: False
#This is the number of times the entire dataset will be passed through the model during training
EPOCHS: 1

CLASSES: 2

WEIGHTS: imagenet
LEARNING_RATE: 0.01
